[colors]
selected_text_color="Black"
selected_bg_color="Yellow"
table_header_color="Yellow"
cpu_core_colors=["Yellow", "Red", "Blue", "Magenta", "Green", "Cyan", "LightYellow", "LightRed"]
avg_cpu_color="Blue"
all_cpu_color="Yellow"
ram_color="Yellow"
swap_color="Red"
rx_color="Magenta"
tx_color="Blue"
widget_title_color="Yellow"
border_color="Yellow"
highlighted_border_color="Red"
text_color="White"
graph_color="White"
cursor_color="White"
scroll_entry_text_color="White"
scroll_entry_bg_color="Red"
high_battery_color="Green"
medium_battery_color="Yellow"
low_battery_color="Red"
gpu_core_colors=["Yellow", "Red", "Blue"]
arc_color="White"
