AllCops:
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 80

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
