wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 6, 6, 6, 90]
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        # From https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        - Tokyo: "Asia/Tokyo"
        - Mexico: "America/Mexico_City"
        - UTC: "Etc/UTC"
      timeFormat: 3:04PM
      position:
        top: 3
        left: 0
        height: 1
        width: 3
      refreshInterval: 15s
      # Valid options are: alphabetical, chronological, natural
      sort: "alphabetical"

    tokyo:
      type: prettyweather
      enabled: true
      city: "tokyo"
      position:
          top: 4
          left: 0
          height: 2
          width: 1
      refreshInterval: 10m
      unit: "m"
      view: 0
      language: "en"
      title: "Tokyo"

    mexico:
      type: prettyweather
      enabled: true
      city: "mexico"
      position:
          top: 4
          left: 1
          height: 2
          width: 1
      refreshInterval: 10m
      unit: "m"
      view: 0
      language: "en"
      title: "CDMX"

    alaska:
      type: prettyweather
      enabled: true
      city: "alaska"
      position:
          top: 4
          left: 2
          height: 2
          width: 1
      refreshInterval: 10m
      unit: "m"
      view: 0
      language: "en"
      title: "Alaska"

    clock:
      type: cmdrunner
      args: []
      cmd: "/Users/mluna/.config/wtf/scripts/time.sh"
      enabled: true
      position:
        top: 1
        left: 0
        height: 2
        width: 3
      refreshInterval: 1s
      enabled: true
      focusable: false
      title: "Time"
      border: true

    dotfiles:
      type: cmdrunner
      enabled: true
      args: []
      title: "Dotfiles"
      focusable: false
      cmd: "/Users/mluna/.config/wtf/scripts/dotfiles.sh"
      position:
        top: 0
        left: 0
        height: 1
        width: 3
      refreshInterval: 8s
