require('core.maps')

nmap("<C-Left>", ":vertical resize -2<CR>")
nmap("<C-Right>", ":vertical resize +2<CR>")
nmap("<C-Up>", ":resize +2<CR>")
nmap("<C-Down>", ":resize -2<CR>")
nmap("Y", "v$hy")
nmap("SS", ":w<CR>")
nmap("ss", ":noautocmd w<CR>")
nmap("gt", ":BufferLineCycleNext<CR>")
nmap("gr", ":BufferLineCyclePrev<CR>")
nmap("gT", ":BufferLineMoveNext<CR>")
nmap("gR", ":BufferLineMovePrev<CR>")
nmap("<Leader>fd", ":Telescope buffers<CR>")
nmap("TT", ":only<CR>")
nmap("tt", ":Bdelete<CR>")
nmap("dh", ":noh<CR>")
nmap("Y", "y$")
nmap("''", "``")
nmap("!", ":ls<CR>")
nmap("<Leader>wk", ":wincmd k<CR>")
nmap("<Leader>wj", ":wincmd j<CR>")
nmap("<Leader>wh", ":wincmd h<CR>")
nmap("<Leader>wl", ":wincmd l<CR>")
nmap("<Leader>ww", "<C-w><C-w>")
nmap("<Leader>ws", "<C-w>s")
nmap("<Leader>wv", "<C-w>v")
nmap("<Leader>wd", "<C-w>q")
nmap("<Leader>gg", "G")
nmap("<Leader>q", ":q")
nmap("<Leader>v", "<C-v>")
nmap("-", "<C-e>")
nmap("¿", "<C-y>")
imap("jj", "<ESC>")
nmap("<Space>", "<Nop>")
nmap("/", ":Telescope current_buffer_fuzzy_find<CR>")
vim.cmd("command Close :bufdo bd | Dashboard")
vim.cmd("command -nargs=* Figlet :read!figlet -w 80 -f larry3d <args>")
