theme:
  name: "custom" # controls the color scheme
  primary: "#c4b28a"
  secondary: "#8992a7"
  error: "#c4746e"
  inactive: "#a6a69c"
  success: "#87a987"

  chromaStyleOverrides: # override parts of the chroma style
