#! /bin/sh

pgrep sxhkd || sxhkd &
pgrep picom && killall picom
pgrep polybar && killall polybar

# Reconfigures monitor
if xrandr | grep -i "HDMI-1 disconnected"; then
	xrandr --output eDP-1 --mode 1366x768 --auto && xrandr --output HDMI-1 --off
  bspc monitor -g 1366x768+0+0
else
	xrandr --output HDMI-1 --mode 1920x1080 && xrandr --output eDP-1 --off
  bspc monitor -g 1920x1080+0+0
fi

# set wallpaper
~/.local/scripts/wallpaper.sh &

# compositor
picom --config ~/.config/picom/picom.conf &

~/.config/polybar/launch.sh &

bspc config border_width         0
bspc config window_gap           0
bspc config top_padding          30

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
