#! /bin/sh

pkill sxhkd; sxhkd &
killall picom

# Reconfigures monitor
if xrandr | grep -i "HDMI-1 disconnected"; then
	xrandr --output eDP-1 && xrandr --output HDMI-1 --off
  bspc monitor --remove HDMI-1
  bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
else
	xrandr --output HDMI-1 --mode 1920x1080 && xrandr --output eDP-1 --off
  bspc monitor --remove eDP-1
  bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X
fi

# set wallpaper
~/.local/scripts/wallpaper.sh &

# compositor
picom --config ~/.config/picom/picom.conf &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
