use_nerdfont = true
flip_status_indicators = true
volnorm = true
library_tabs = ["tracks", "albums", "artists", "playlists"]

[keybindings]
"Ctrl+f" = "focus search"
"Ctrl+l" = "focus library"
"Ctrl+q" = "focus queue"
"[" = "move up 10"
"]" = "move down 10"
"g" = "move up 5000"
"G" = "move down 5000"
"q" = "noop"
"Shift+q" = "quit"
