#!/usr/bin/env bash

remote="$1"
url="$2"

exec < /dev/tty

printf "You are pushing to %s (%s), are you sure? [Ny] " "$remote" "$url"
read -r resp
resp=$(tr '[:upper:]' '[:lower:]' <<< "$resp")

if [ "$resp" != y ]; then
	printf "Aborted.\n"
	exit 1
fi

exit
