[[themes]]
name = "kanagawa-dragon"
[themes.palette]
background = "#282727"
foreground = "#c8c093"
black = "#0d0c0c"
red = "#c4746e"
green = "#8a9a7b"
yellow = "#c4b28a"
blue = "#8ba4b0"
magenta = "#a292a3"
cyan = "#8ea4a2"
white = "#c8c093"
bright_black = "#a6a69c"
bright_red = "#e46876"
bright_green = "#87a987"
bright_yellow = "#e6c384"
bright_blue = "#7fb4ca"
bright_magenta = "#938aa9"
bright_cyan = "#7aa89f"
bright_white = "#c5c9c5"
[themes.component_style]
block_title = { fg = "Red"  }
border = { fg = "Red" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "BrightBlack" }
playback_progress_bar = { bg = "Red", fg = "Black" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
selection = { modifiers = ["Bold", "Reversed"] }
